# ============================================================
# Amazon Recommendation Engine - Base Configuration
# ============================================================
# This is the base configuration file for all environments
# Environment-specific overrides should be placed in:
# - development.yaml, staging.yaml, or production.yaml

# ============================================================
# General Settings
# ============================================================
environment: development  # development, staging, production

# ============================================================
# API Settings
# ============================================================
api:
  host: 0.0.0.0
  port: 5050
  threads: 4
  debug: false
  request_timeout: 30  # seconds
  max_content_length: 16777216  # 16MB in bytes
  enable_cors: true
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:3001"

# ============================================================
# Database Settings
# ============================================================
database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: recommender
  pool_size: 10
  max_overflow: 20
  pool_timeout: 30

# ============================================================
# Redis Cache Settings
# ============================================================
redis:
  host: localhost
  port: 6379
  db: 0
  password: null  # Set to null for no password
  socket_timeout: 5
  key_prefix: "rec:"
  ttl: 3600  # default cache TTL in seconds (1 hour)

# ============================================================
# Kafka Settings
# ============================================================
kafka:
  bootstrap_servers: localhost:9092
  enable: true  # Set to false to disable Kafka integration
  topics:
    product_events: product-events
    recommendations: recommendations
    metrics: metrics
  consumer_group: recommender-api
  auto_offset_reset: earliest
  connections:
    max_in_flight_requests_per_connection: 5
    message_timeout_ms: 30000  # 30 seconds
    session_timeout_ms: 30000  # 30 seconds

# ============================================================
# Model Settings
# ============================================================
models:
  path: data/models
  cache_size: 10000  # Number of user vectors to keep in memory
  default_model: lightgcn  # Default model to use
  max_recommendations: 100
  default_recommendations: 10
  score_threshold: 0.01  # Minimum score to include in recommendations
  cold_start_strategy: popular  # popular, random, content-based
  update_interval: 3600  # How often to reload models (seconds)
  preload_models:  # Models to load at startup
    - lightgcn
    - ncf
    - mf
  ensemble:
    weights:
      lightgcn: 0.35
      ncf: 0.25
      mf: 0.25
      content_based: 0.15

# ============================================================
# Feedback Loop Settings
# ============================================================
feedback_loop:
  enable: true
  window_size: 48  # hours
  minimum_events: 10  # Minimum number of events to process
  update_interval: 3600  # seconds between updates
  event_weights:
    click: 1.0
    view: 0.5
    purchase: 5.0
    add_to_cart: 2.0
    rate: 3.0

# ============================================================
# Logging Settings
# ============================================================
logging:
  level: INFO  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: logs/api.log
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  max_size: 10485760  # 10MB in bytes
  backup_count: 5
  console: true  # Whether to also log to console

# ============================================================
# Metrics Settings
# ============================================================
metrics:
  enable: true
  port: 8001
  path: /metrics
  collection_interval: 15  # seconds between metric collections
  include_model_metrics: true
  include_api_metrics: true
  include_system_metrics: true

# ============================================================
# Testing Settings
# ============================================================
testing:
  test_user_ids:
    - A12BCD34EFG56H
    - B98FED76CBA54G
    - C13579ACE24680
  sample_size: 1000
  random_seed: 42
