global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'recommendation_api'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['api:5050']

  - job_name: 'recommendation_metrics'
    scrape_interval: 30s
    metrics_path: /metrics
    static_configs:
      - targets: ['metrics:8001']

  - job_name: 'kafka'
    metrics_path: /metrics
    static_configs:
      - targets: ['kafka:9308']

  - job_name: 'postgres'
    metrics_path: /metrics
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'stream_processor'
    metrics_path: /metrics
    static_configs:
      - targets: ['stream-processor:8002']

  - job_name: 'node-exporter'
    metrics_path: /metrics
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'metrics-exporter'
    metrics_path: /metrics
    static_configs:
      - targets: ['metrics-exporter:9113'] 