
# This file is automatically generated to patch the database connection
# when PostgreSQL is not available

def mock_init_db():
    """Mock implementation of init_db that doesn't connect to the database."""
    print("DATABASE PATCHED: Using mock database initialization")
    return True

# Monkey patch the real init_db with our mock version
import sys
import importlib.util
try:
    # Try to import the real database module
    spec = importlib.util.find_spec('src.data.database')
    if spec:
        database = importlib.util.module_from_spec(spec)
        sys.modules['src.data.database'] = database
        spec.loader.exec_module(database)
        
        # Replace the real init_db with our mock version
        database.init_db = mock_init_db
        print("DATABASE PATCHED: Successfully patched database module")
except Exception as e:
    print(f"DATABASE PATCHED: Error patching database module: {e}")
